apiVersion: apps/v1
kind: Deployment
metadata:
  name: web2-hard-pod-deployment
  namespace: default
  labels:
    name: web2-hard-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: web2-hard
  template:
    metadata:
      labels:
        name: web2-hard
    spec:
      containers:  
        - name: node
          image: gcr.io/rosy-cache-200605/nginx-hard-pvr
          imagePullPolicy: IfNotPresent 
          ports:
            - containerPort: 8080
