apiVersion: v1 
kind: Service
metadata:
  name: web2-hard-service
  namespace: default
spec:
  selector:
    name: web2-hard
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
